latest batch of changes

diff --git a/scripts/.local/bin/flash b/scripts/.local/bin/flash
--- a/scripts/.local/bin/flash
+++ b/scripts/.local/bin/flash
@@ -26,6 +26,7 @@
 # USER CUSTOMIZABLE VARIABLES
     CARD_POOL_SIZE=10 # How large the pool size is for shuf to draw from
     SEARCH_DEPTH=999  # How many levels to recursively search for .csv's in .local/share/flash
+    PREVIEWER='bat'   # What fzf previewer to use when searching through decks
 
 # ANSI FOREGROUND ESCAPE COLORS
     RED='\033[0;31m'
@@ -52,7 +53,7 @@
 # Prefer XDG Configuration before hard coded file paths
     OS="$(uname)"
     case "$OS" in
-        "Darwin") DIR="${XDG_DATA_HOME:-HOME/Library/Application Support}/flash" ;;
+        "Darwin") DIR="${XDG_DATA_HOME:-$HOME/Library/Application Support}/flash" && alias shuf=gshuf ;;
         "Linux") DIR="${XDG_DATA_HOME:-$HOME/.local/share}/flash" ;;
         *) DIR="${XDG_DATA_HOME:-$HOME/.local/share}/flash" ;;
     esac
@@ -68,6 +69,8 @@
 DIR_MADE_MSG="
 Your ${LRED}$DIR${NC} directory has been made and
 your ${ORANGE}deck.csv${NC} file is ready for you to enter your flashcard data
+If you want to see information about ${ORANGE}fla.sh${NC} then use the option
+${YELLOW}flash -i${NC}.
 "
 # User has .local/share directory but no decks inside
 NO_DECKS="
@@ -112,10 +115,9 @@ Programming:What is the best operating system?:Arch, because BTW i run Arch:999"
 # Define setup process in a function and create necessary files for user
 setup(){\
     mkdir "$DIR" && \
-    eval touch {"$EXAMPLE_DECK","$HIGH_SCORE","$REVIEW_LOG"} && \
+    touch {"$EXAMPLE_DECK","$HIGH_SCORE","$REVIEW_LOG"} && \
     echo "$DECK_TEMPLATE" >> "$EXAMPLE_DECK" && \
-    echo -e "$DIR_MADE_MSG" \
-;}
+    echo -e "$DIR_MADE_MSG" ;}
 
 # Test if .local/share exists and wether to offer setup process
 if [ ! -d "$DIR" ];then
@@ -149,7 +151,7 @@ if [ ! -e "$REVIEW_LOG" ]; then
 fi
 
 print_usage() {
-    echo -e "\n${LCYAN}fla.sh --- Flash card system by Bryan Jenks${NC} ${LBLUE}<BryanJenks@protonmail.com>${NC}\n\n${YELLOW}${BOLD}Usage:${NC}\n\t${GREEN}flash -h:${NC} Print this help text\n\t${GREEN}flash -i:${NC} Print Information about the flashcard system\n\t${GREEN}flash -v:${NC} Print version Number\n\n"
+    echo -e "\n${LCYAN}fla.sh --- Flash card system by Bryan Jenks${NC} ${LBLUE}<BryanJenks@protonmail.com>${NC}\n\n${YELLOW}${BOLD}Usage:${NC}\n\t${GREEN}flash -h:${NC} Print this help text\n\t${GREEN}flash -i:${NC} Print Information about the flashcard system\n\t${GREEN}flash -v:${NC} Print version Number\n\t${GREEN}flash -p [BINARY]:${NC} Change the previewer when selecting decks.\n\t\tDefault: ${GREEN}bat${NC}\n\t\tSupported: ${GREEN}bat${NC}, ${GREEN}cat${NC}\n"
 }
 
 print_info() {
@@ -195,18 +197,28 @@ ${LCYAN}The Scoring System:${NC}\n
 "
 }
 
-while getopts 'hiv' flag; do
+while getopts 'hivp:' flag; do
   case "${flag}" in
     h) print_usage && exit ;;
     i) print_info && exit ;;
     v) echo -e "\n${YELLOW}fla.sh Current Version:${NC} ${RED}1.1${NC}\n" && exit ;;
+    p) if [[ $(command -v "$OPTARG" 2>&1) ]]; then PREVIEWER=$OPTARG; else echo "Unable to find previewer $OPTARG. Exiting..." && exit 1; fi ;;
     *) print_usage && exit 1 ;;
   esac
 done
 
 
-# Show pretty FZF preview of decks using BAT
-    DECK="$(find . -maxdepth "$SEARCH_DEPTH" -iname "*.csv" | fzf --preview='bat --theme="Solarized (dark)" --style=numbers --color=always {} | head -500')"
+# Set some parameters for preview command used by FZF
+while [ -z "$PREVIEWER_PARAMTERS" ]; do
+  case "$PREVIEWER" in
+    bat) PREVIEWER_PARAMTERS="--theme='Solarized (dark)' --style=numbers --color=always" ;;
+    cat) PREVIEWER_PARAMTERS="--number" ;;
+    *)   echo -e "${RED}$PREVIEWER${NC} is not a valid previewer. Use '${GREEN}bat${NC}' or '${GREEN}cat${NC}'. Falling back on default...\n" && read -r -s -p 'Press [Enter] to continue...' && echo -e "\n" && PREVIEWER='bat' ;;
+  esac
+done
+
+# Show pretty FZF preview of decks using $PREVIEWER. Default: BAT
+    DECK="$(find . -maxdepth "$SEARCH_DEPTH" -iname "*.csv" | fzf --preview="$PREVIEWER $PREVIEWER_PARAMTERS {} | head -500")"
 
 # If no deck is selected in fzf menu
 # return user to start location
@@ -220,16 +232,16 @@ main(){
     # shellcheck disable=SC2162
     read -a q <<< "$(sort "$DECK" -n --field-separator=: --key=4 | head -n "$CARD_POOL_SIZE"| shuf -n 1)"
     clear
-    echo -e "${WHITEBG}          Fla.sh - Flash Cards In Your Terminal            ${NC}"
-    echo -e "${ORANGE}${BOLD}Cards Reviewed:${BOLD}${NC}\t$COUNTER"
-    echo -e "\t${ORANGE}${BOLD}High Score:${BOLD}${NC}\t$(cat "$HIGH_SCORE")"
-    echo -e "\t${ORANGE}${BOLD}Avg review:${BOLD}${NC}\t$(awk '{ sum += $7; n++ } END { if (n > 0) print sum / n; }' "$REVIEW_LOG")"
-    echo -e ""
-    echo -e "${LGREY}Category:${NC}\n\t\t${q[0]}"
-    echo -e "${LGREY}Question:${NC}\n\t\t${q[1]}"
-    echo -e ""
-    echo -e ""
-    echo -e "${LGREY}Press [Enter] to continue...${NC}"
+    echo -e "${WHITEBG}          Fla.sh - Flash Cards In Your Terminal            ${NC}
+${ORANGE}${BOLD}Cards Reviewed:${BOLD}${NC}\t$COUNTER
+\t${ORANGE}${BOLD}High Score:${BOLD}${NC}\t$(cat "$HIGH_SCORE")
+\t${ORANGE}${BOLD}Avg review:${BOLD}${NC}\t$(awk '{ sum += $7; n++ } END { if (n > 0) print sum / n; }' "$REVIEW_LOG")
+
+${LGREY}Category:${NC}\n\t\t${q[0]}
+${LGREY}Question:${NC}\n\t\t${q[1]}
+
+
+${LGREY}Press [Enter] to continue...${NC}"
     # shellcheck disable=SC2162
     read -sn 1 NEXT
     while [ ! "$NEXT" = "" ] && [ ! "$NEXT" = q ] && [ ! "$NEXT" = Q ]; do
@@ -237,26 +249,26 @@ main(){
         read -sn 1 NEXT
     done
     clear
-    echo -e "${WHITEBG}          Fla.sh - Flash Cards In Your Terminal            ${NC}"
-    echo -e "${ORANGE}${BOLD}Cards Reviewed:${BOLD}${NC}\t$COUNTER"
-    echo -e "\t${ORANGE}${BOLD}High Score:${BOLD}${NC}\t$(cat "$HIGH_SCORE")"
-    echo -e "\t${ORANGE}${BOLD}Avg review:${BOLD}${NC}\t$(awk '{ sum += $7; n++ } END { if (n > 0) print sum / n; }' "$REVIEW_LOG")"
-    echo -e ""
-    echo -e "${LGREY}Category:${NC}\n\t\t${q[0]}"
-    echo -e "${LGREY}Question:${NC}\n\t\t${q[1]}"
-    echo -e ""
+    echo -e "${WHITEBG}          Fla.sh - Flash Cards In Your Terminal            ${NC}
+${ORANGE}${BOLD}Cards Reviewed:${BOLD}${NC}\t$COUNTER
+\t${ORANGE}${BOLD}High Score:${BOLD}${NC}\t$(cat "$HIGH_SCORE")
+\t${ORANGE}${BOLD}Avg review:${BOLD}${NC}\t$(awk '{ sum += $7; n++ } END { if (n > 0) print sum / n; }' "$REVIEW_LOG")
+
+${LGREY}Category:${NC}\n\t\t${q[0]}
+${LGREY}Question:${NC}\n\t\t${q[1]}
+"
     if [ "$NEXT" = q ] || [ "$NEXT" = Q ]; then
         add_usage_entry && cd "$PWD" && clear && exit
     fi
-    echo -e "${LGREY}Answer:${NC}\n\t\t${q[2]}"
-    echo -e ""
-    echo -e "${WHITEBG}${WHITE}===========================================================${NC}"
-    echo -e ""
-    echo -e "${LGREY}How Difficult Was This Question?${NC}"
-    echo -e ""
-    echo -e "${LRED}Hard${NC} [1]   ${RED}Difficult${NC} [2]   ${YELLOW}Normal${NC} [3]   ${GREEN}Mild${NC} [4]   ${LGREEN}Easy${NC} [5]"
-    echo -e ""
-    echo -e "${LGREY}Select a number to continue, or${NC} ${LRED}Q${NC} ${LGREY}to quit...${NC}"
+    echo -e "${LGREY}Answer:${NC}\n\t\t${q[2]}
+
+${WHITEBG}${WHITE}===========================================================${NC}
+
+${LGREY}How Difficult Was This Question?${NC}
+
+${LRED}Hard${NC} [1]   ${RED}Difficult${NC} [2]   ${YELLOW}Normal${NC} [3]   ${GREEN}Mild${NC} [4]   ${LGREEN}Easy${NC} [5]
+
+${LGREY}Select a number to continue, or${NC} ${LRED}Q${NC} ${LGREY}to quit...${NC}"
     # shellcheck disable=SC2162
     read -sn 1 DIFFICULTY_SCORE
     while [[ ! "$DIFFICULTY_SCORE" =~ [12345qQ] ]]; do
